<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FlowerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlowerRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findAllExists()
    {
        return $this->getEntityManager()
            ->createQuery("SELECT f
                           FROM AppBundle:Flower f
                           WHERE f.isExists = true")
            ->getResult();
    }
}
