<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    /**
     * @return \Doctrine\ORM\Query
     */
    public function findAllProducts()
    {
        return  $this->getEntityManager()
            ->createQuery("SELECT p
                           FROM AppBundle:Product p
                           LEFT JOIN p.media m")
            ;
    }
}
