services:
    app.admin.product:
        class: AppBundle\Admin\ProductAdmin
        arguments: [~, AppBundle\Entity\Product, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Product}
        calls:
            - [ setTemplate, [edit, AppBundle:Admin:product_edit.html.twig]]


    app.admin.color:
        class: AppBundle\Admin\ColorAdmin
        arguments: [~, AppBundle\Entity\Color, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Color}

    app.admin.flower:
        class: AppBundle\Admin\FlowerAdmin
        arguments: [~, AppBundle\Entity\Flower, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Flower}

    app.form.type.color.picker:
        class: AppBundle\Form\Type\ColorPickerType
        tags:
            - { name: form.type, alias: color_picker }

    app.form.type.picture:
        class: AppBundle\Form\Type\PictureType
        tags:
            - { name: form.type, alias: picture }

    app.form.type.multiple.file:
        class: AppBundle\Form\Type\BBMultipleFileType
        tags:
            - { name: form.type, alias: bb_multiple_file }

    app.admin.product_type:
        class: AppBundle\Admin\ProductTypeAdmin
        arguments: [~, AppBundle\Entity\ProductType, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: ProductType}
